export type ItineraryDay = {
  day: number;
  title: string;
  location: string;
  description: string;
  activities: string[];
  meals: string;
  accommodation: string;
};

export type PremadeItinerary = {
  id: string;
  title: string;
  subtitle: string;
  duration: string;
  durationDays: number;
  difficulty: 'Easy' | 'Moderate' | 'Challenging';
  highlights: string[];
  bestTime: string;
  coverImage: string;
  tags: string[];
  summary: string;
  days: ItineraryDay[];
};

export const premadeItineraries: PremadeItinerary[] = [
  {
    id: 'buddhist-circuit',
    title: 'Tawang Buddhist Circuit',
    subtitle: 'Monasteries, Mountain Passes & Sacred Lakes',
    duration: '7 Days / 6 Nights',
    durationDays: 7,
    difficulty: 'Moderate',
    highlights: ['Tawang Monastery', 'Sela Pass (4170m)', 'Bumla Pass', 'Sangestar Tso Lake', 'Bomdila Monastery'],
    bestTime: 'October – April',
    coverImage: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&h=500&fit=crop&auto=format&q=80',
    tags: ['Spiritual', 'Photography', 'Mountains', 'Culture'],
    summary: '7-day journey through Arunachal\'s Buddhist heartland. Visit Asia\'s largest monastery at Tawang, cross the Sela Pass at 4170m, and discover sacred lakes along the India-China border.',
    days: [
      {
        day: 1,
        title: 'Arrival & Drive to Bhalukpong',
        location: 'Guwahati → Bhalukpong',
        description: 'Fly into Guwahati and drive to Bhalukpong, the gateway to Arunachal Pradesh. Enjoy the transition from plains to forested foothills and get your inner-line permit verified.',
        activities: ['Pickup from Guwahati airport', 'Scenic drive through Assam foothills', 'Cross into Arunachal at Bhalukpong checkpoint', 'Evening walk along Kameng River'],
        meals: 'Dinner at resort',
        accommodation: 'Riverside Resort, Bhalukpong',
      },
      {
        day: 2,
        title: 'Bomdila – The Gateway Monastery Town',
        location: 'Bhalukpong → Bomdila',
        description: 'Drive up through pine forests to the charming hill town of Bomdila at 2700m. Visit the famous Bomdila Monastery and enjoy panoramic views of the Eastern Himalayas.',
        activities: ['Upper Bomdila Monastery visit', 'Lower Bomdila Monastery', 'RR Hills viewpoint', 'Local market walk for handicrafts'],
        meals: 'Breakfast at hotel, Lunch at local café, Dinner at hotel',
        accommodation: 'Hotel Blue Pine, Bomdila',
      },
      {
        day: 3,
        title: 'Dirang – Valley of Hot Springs',
        location: 'Bomdila → Dirang',
        description: 'Drive down to the scenic Dirang Valley, a bowl-shaped settlement surrounded by apple orchards and streams. Visit the ancient Dirang Dzong and soak in natural hot springs.',
        activities: ['Ancient Dirang Dzong fortress exploration', 'Natural hot water springs soak', 'Apple orchard visit (Oct-Nov)', 'Sangti Valley yak farm visit'],
        meals: 'Breakfast at hotel, Lunch at Dirang town, Dinner at guesthouse',
        accommodation: 'Pemaling Guest House, Dirang',
      },
      {
        day: 4,
        title: 'Sela Pass & Jaswant Garh',
        location: 'Dirang → Sela Pass → Tawang',
        description: 'Drive over the iconic Sela Pass at 4170m — one of the world\'s highest motorable roads. Stop at the sacred Sela Lake and pay homage at the Jaswant Garh war memorial.',
        activities: ['Sela Pass crossing (4170m elevation)', 'Sela Lake photography stop', 'Jaswant Garh war memorial visit', 'Nuranang (Jung) Waterfall viewpoint'],
        meals: 'Packed breakfast, Hot lunch at Sela Pass café, Dinner at hotel',
        accommodation: 'Hotel Pemaling, Tawang',
      },
      {
        day: 5,
        title: 'Tawang – The Jewel of the Himalayas',
        location: 'Tawang',
        description: 'Full day to explore Tawang town. The centrepiece is the magnificent Tawang Monastery — the largest Buddhist monastery in India and second largest in Asia, perched at 3500m.',
        activities: ['Tawang Monastery (Galden Namgyal Lhatse) guided tour', 'Tawang War Memorial & museum', 'Ani Gompa (nunnery) visit', 'Local market for Monpa handicrafts and yak wool'],
        meals: 'Breakfast at hotel, Lunch at monastery café, Dinner with local Monpa feast',
        accommodation: 'Hotel Pemaling, Tawang',
      },
      {
        day: 6,
        title: 'Bumla Pass & Sangestar Tso Lake',
        location: 'Tawang → Bumla (37km from China border)',
        description: 'Drive to Bumla Pass at 4563m on the India–China border — a special permit is required. The sacred Sangestar Tso (P.T. Tso) Lake offers surreal high-altitude beauty.',
        activities: ['Bumla Pass border viewpoint (special permit required)', 'Sangestar Tso (P.T. Tso) Lake trek', 'Madhuri Lake (Shungetser) photography', 'Return to Tawang for shopping'],
        meals: 'Packed breakfast, Lunch at Bumla tea post, Dinner at hotel',
        accommodation: 'Hotel Pemaling, Tawang',
      },
      {
        day: 7,
        title: 'Return Journey',
        location: 'Tawang → Guwahati',
        description: 'Begin the return drive to Guwahati. Stop at Dirang for lunch and enjoy the final mountain views before the descent into the plains for your return flight.',
        activities: ['Morning Tawang town walk', 'Drive via Sela Pass', 'Lunch stop at Dirang', 'Evening arrival at Guwahati'],
        meals: 'Breakfast at hotel, Lunch at Dirang, Dinner at Guwahati',
        accommodation: 'Hotel in Guwahati (own arrangements)',
      },
    ],
  },
  {
    id: 'wildlife-explorer',
    title: 'Wildlife & Birding Explorer',
    subtitle: 'Tigers, Hoolock Gibbons & 500+ Bird Species',
    duration: '5 Days / 4 Nights',
    durationDays: 5,
    difficulty: 'Easy',
    highlights: ['Namdapha National Park', 'Pakke Tiger Reserve', 'Hoolock Gibbon tracking', 'Hornbill Festival', 'Glow-in-dark mushroom forest'],
    bestTime: 'November – April',
    coverImage: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&h=500&fit=crop&auto=format&q=80',
    tags: ['Wildlife', 'Birding', 'Nature', 'Photography'],
    summary: '5-day wildlife immersion in Arunachal\'s biodiversity hotspots. Track tigers and elephants in Namdapha, spot the rare Hoolock Gibbon, and discover one of the richest bird habitats on Earth.',
    days: [
      {
        day: 1,
        title: 'Arrival at Dibrugarh & Drive to Miao',
        location: 'Dibrugarh → Miao (Namdapha Buffer Zone)',
        description: 'Fly into Dibrugarh and drive to Miao, the base camp for Namdapha National Park. Attend an evening briefing on wildlife tracking safety and permit procedures.',
        activities: ['Airport pickup at Dibrugarh', 'Drive through Assam tea gardens', 'Cross into Arunachal at Changlang', 'Evening wildlife briefing at Forest Rest House'],
        meals: 'Dinner at forest guesthouse',
        accommodation: 'Namdapha Forest Rest House, Miao',
      },
      {
        day: 2,
        title: 'Namdapha Core Zone Safari',
        location: 'Namdapha National Park',
        description: 'Full-day guided jungle walk and jeep safari in the core zone of Namdapha — the only park in India with 4 big cat species. Dawn birding session along the Noa-Dehing River.',
        activities: ['Dawn birding walk along Noa-Dehing River', 'Guided jungle safari (elephant, tiger, leopard, clouded leopard habitat)', 'Hoolock Gibbon tracking in forest canopy', 'Butterfly and moth spotting (450+ species)'],
        meals: 'Packed breakfast, Jungle lunch, Dinner at guesthouse',
        accommodation: 'Namdapha Forest Rest House, Miao',
      },
      {
        day: 3,
        title: 'Deban Camp & Night Walk',
        location: 'Namdapha Deep Forest – Deban Camp',
        description: 'Trek deeper into Namdapha to Deban camp at the confluence of two rivers. Spot the rare Mishmi Takin and an extraordinary diversity of hornbills. Night wildlife walk with headlamps.',
        activities: ['5km trek to Deban riverside camp', 'Great Hornbill & Wreathed Hornbill spotting', 'Freshwater fishing (permit required)', 'Guided night wildlife walk'],
        meals: 'Packed meals throughout, Campfire dinner',
        accommodation: 'Deban Forest Camp (tented)',
      },
      {
        day: 4,
        title: 'Pakke Tiger Reserve',
        location: 'Miao → Pakke (Seijosa)',
        description: 'Drive to Pakke Tiger Reserve in East Kameng — a UNESCO biosphere reserve and stronghold for the endangered Wreathed Hornbill. Elephant-back safari at dusk.',
        activities: ['Morning departure from Namdapha', 'Pakke River Nature Trail', 'Elephant safari at dusk through tall grass', 'Hornbill nest monitoring project visit'],
        meals: 'Breakfast at guesthouse, Lunch en route, Dinner at Pakke',
        accommodation: 'Pakke Wildlife Camp, Seijosa',
      },
      {
        day: 5,
        title: 'Pakke Morning Safari & Departure',
        location: 'Pakke → Tezpur Airport',
        description: 'Last dawn safari in Pakke before checking out. Drive to Tezpur for your return flight, passing through the beautiful Kameng valley and Bhalukpong checkpoint.',
        activities: ['6am dawn jungle safari', 'Bird photography at river viewpoint', 'Visit to Pakke Nature Interpretation Centre', 'Drive to Tezpur for departure'],
        meals: 'Breakfast at camp, Lunch en route to Tezpur',
        accommodation: 'Departure',
      },
    ],
  },
  {
    id: 'tribal-heritage',
    title: 'Tribal Heritage & Culture Trail',
    subtitle: 'Apatani Villages, Rice Beer & Living Traditions',
    duration: '6 Days / 5 Nights',
    durationDays: 6,
    difficulty: 'Easy',
    highlights: ['Ziro Valley (UNESCO Tentative List)', 'Apatani tribe villages', 'Dree Festival', 'Pasighat riverside', 'Adi tribal homestay'],
    bestTime: 'July (Dree Festival) / October – March',
    coverImage: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&h=500&fit=crop&auto=format&q=80',
    tags: ['Culture', 'Tribal', 'Heritage', 'Festivals'],
    summary: '6-day deep dive into Arunachal\'s tribal heartland. Live with the Apatani tribe in Ziro Valley\'s bamboo villages, witness ancient fishing rituals at Pasighat, and participate in harvest festivals.',
    days: [
      {
        day: 1,
        title: 'Arrival at Itanagar & Drive to Ziro',
        location: 'Itanagar → Ziro Valley',
        description: 'Fly or drive to Itanagar, the state capital. Head to the scenic Ziro Valley — a UNESCO World Heritage tentative site, home to the Apatani tribe and their extraordinary rice paddy-fish farming system.',
        activities: ['Arrival at Naharlagun/Itanagar', 'Drive to Ziro Valley (4-5 hours)', 'Check into Apatani homestay', 'Evening introduction to Apatani customs with host family'],
        meals: 'Welcome dinner with Apatani family',
        accommodation: 'Apatani Homestay, Hong Village, Ziro',
      },
      {
        day: 2,
        title: 'Ziro Valley Village Walk',
        location: 'Ziro Valley – Apatani Villages',
        description: 'Full day exploring the seven Apatani villages. Learn about the unique nose plug and tattoo traditions of Apatani women, see the innovative paddy-cum-fish cultivation, and visit the craft weavers.',
        activities: ['Guided walk through Hong, Hari & Dutta villages', 'Traditional Apatani weaving demonstration', 'Paddy field and fish farming walk', 'Nishi tribal craft market in Ziro town'],
        meals: 'Breakfast & dinner at homestay, Lunch at village tea stall',
        accommodation: 'Apatani Homestay, Hong Village, Ziro',
      },
      {
        day: 3,
        title: 'Talley Valley Wildlife Sanctuary Trek',
        location: 'Ziro → Talley Valley',
        description: 'Trek into the Talley Valley Wildlife Sanctuary — a pristine temperate broadleaf forest above Ziro. Spot the rare Mishmi Wren Babbler, black bears, and the protected clouded leopard.',
        activities: ['8km guided trek into Talley Valley', 'Birding with local expert guide', 'Alpine meadow picnic lunch', 'Sunset at Pine Grove viewpoint'],
        meals: 'Packed lunch, Dinner at homestay',
        accommodation: 'Apatani Homestay, Hong Village, Ziro',
      },
      {
        day: 4,
        title: 'Drive to Along (Aalo) – Adi Heartland',
        location: 'Ziro → Along (Aalo)',
        description: 'Drive to Along on the banks of the mighty Siang River, the principal town of the Adi tribe. The journey crosses high ridges with sweeping valley views.',
        activities: ['Morning departure from Ziro', 'Scenic mountain drive via Daporijo', 'Check-in to Along guesthouse', 'Evening walk to Siang riverbank'],
        meals: 'Breakfast at homestay, Lunch en route, Dinner in Along',
        accommodation: 'Hotel Siang, Along',
      },
      {
        day: 5,
        title: 'Siang River Rafting & Adi Village',
        location: 'Along (Aalo)',
        description: 'Spend the day with the Adi tribe. Visit a traditional Adi village with their distinctive longhouses, participate in rice beer brewing, and try white-water rafting on the powerful Siang.',
        activities: ['Adi village visit & longhouse tour', 'Traditional rice beer brewing demo & tasting', 'Grade II-III white-water rafting on Siang River', 'Evening cultural performance by Adi youth group'],
        meals: 'Breakfast at hotel, Village lunch with Adi family, Dinner at hotel',
        accommodation: 'Hotel Siang, Along',
      },
      {
        day: 6,
        title: 'Pasighat – Siang Valley Finale',
        location: 'Along → Pasighat',
        description: 'Drive to Pasighat, the oldest town in Arunachal Pradesh on the banks of the Brahmaputra (Siang). Explore the riverside markets and depart from Dibrugarh airport.',
        activities: ['Morning drive to Pasighat', 'Pasighat riverside market & Adi craft shops', 'Siang-Brahmaputra confluence viewpoint', 'Afternoon flight or drive to Dibrugarh'],
        meals: 'Breakfast at hotel, Lunch at Pasighat dhaba',
        accommodation: 'Departure',
      },
    ],
  },
  {
    id: 'adventure-trek',
    title: 'Mechuka Adventure & Trekking',
    subtitle: 'Remote Valleys, Ancient Monasteries & River Rafting',
    duration: '8 Days / 7 Nights',
    durationDays: 8,
    difficulty: 'Challenging',
    highlights: ['Mechuka Valley', 'Samten Yongcha Monastery', 'Siyom River rafting', 'Kidi Village trek', 'Remote tribal homestays'],
    bestTime: 'October – December, March – May',
    coverImage: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=500&fit=crop&auto=format&q=80',
    tags: ['Adventure', 'Trekking', 'Remote', 'Rafting'],
    summary: '8-day adventure into one of India\'s most remote valleys. Trek to hidden Memba tribe villages in Mechuka, raft the wild Siyom River, and discover untouched landscapes near the Tibet border.',
    days: [
      {
        day: 1,
        title: 'Arrival at Dibrugarh & Overnight Drive',
        location: 'Dibrugarh → Along (Aalo)',
        description: 'Arrive at Dibrugarh and begin the overnight drive or day drive to Along, the base for the Mechuka circuit. The road follows the mighty Brahmaputra through tribal Assam and Lower Siang.',
        activities: ['Airport pickup Dibrugarh', 'Drive via Pasighat to Along', 'Evening gear check and trek briefing', 'Overnight at Along guesthouse'],
        meals: 'Dinner at Along',
        accommodation: 'Hotel Siang, Along',
      },
      {
        day: 2,
        title: 'Along → Mechuka (Incredible Drive)',
        location: 'Along → Mechuka Valley',
        description: 'The 6-7 hour drive to Mechuka is an adventure in itself — winding mountain roads above gorges, through dense forest, and across hanging bridges over the Siyom River.',
        activities: ['Early departure from Along', 'Siyom River gorge drives with photo stops', 'Crossing hanging bridge at Yomcha', 'Arrival at Mechuka valley at sunset'],
        meals: 'Packed breakfast, Lunch at roadside dhaba, Dinner at guesthouse',
        accommodation: 'Mechuka Valley Guesthouse',
      },
      {
        day: 3,
        title: 'Mechuka Valley Exploration',
        location: 'Mechuka',
        description: 'Spend a full day exploring the magical Mechuka Valley — a hidden paradise near the Tibet border at 1800m. Visit the ancient Samten Yongcha Monastery and Memba tribe villages.',
        activities: ['Samten Yongcha Buddhist Monastery (800 years old)', 'Mechuka village walk with Memba tribe interactions', 'Tibetan-influenced craft market', 'Apple orchard and paddy field walk'],
        meals: 'Breakfast & dinner at guesthouse, Lunch with Memba family',
        accommodation: 'Mechuka Valley Guesthouse',
      },
      {
        day: 4,
        title: 'Kidi Village Trek (High Altitude)',
        location: 'Mechuka → Kidi Village (14km trek)',
        description: 'Trek to Kidi village through pristine rhododendron forests and alpine meadows. This challenging day hike rewards with views of snow-covered peaks along the Tibet border.',
        activities: ['14km guided trek to Kidi village', 'Rhododendron and alpine flower fields', 'Views of Tibetan border peaks', 'Overnight at traditional Memba homestay in Kidi'],
        meals: 'Packed breakfast, Homestay meals in Kidi',
        accommodation: 'Memba Tribal Homestay, Kidi Village',
      },
      {
        day: 5,
        title: 'Return Trek & Siyom River Camp',
        location: 'Kidi → Mechuka → Siyom River Camp',
        description: 'Trek back to Mechuka and drive downstream to the Siyom River base camp for two days of white-water rafting preparation.',
        activities: ['Morning return trek from Kidi', 'Afternoon drive to Siyom River camp', 'Rafting safety briefing with expert guides', 'Campfire evening with local music'],
        meals: 'Breakfast at homestay, Lunch in Mechuka, Campfire dinner',
        accommodation: 'Siyom River Camp (tented)',
      },
      {
        day: 6,
        title: 'Siyom River Rafting – Day 1',
        location: 'Siyom River',
        description: 'Full day white-water rafting on the Grade III-IV Siyom River — one of Arunachal\'s best rafting rivers. Navigate dramatic gorges and forested canyon walls.',
        activities: ['Grade III-IV white-water rafting (25km stretch)', 'Cliff-jumping at safe spots with guides', 'Riverside lunch on a gravel beach', 'Sunset photography at gorge viewpoint'],
        meals: 'Breakfast at camp, Riverside picnic lunch, Dinner at camp',
        accommodation: 'Siyom River Camp (tented)',
      },
      {
        day: 7,
        title: 'Siyom River Rafting – Day 2 & Drive to Along',
        location: 'Siyom River → Along',
        description: 'Morning rafting on calmer stretches, then drive back to Along for a well-deserved rest and hot shower.',
        activities: ['Morning gentle rafting (10km)', 'Riverside tribal fishing technique demo', 'Afternoon drive to Along', 'Evening rest and Along market walk'],
        meals: 'Packed breakfast, Lunch en route, Dinner at Along',
        accommodation: 'Hotel Siang, Along',
      },
      {
        day: 8,
        title: 'Departure from Pasighat',
        location: 'Along → Pasighat → Dibrugarh',
        description: 'Final morning drive to Pasighat with one last stop at the Siang-Brahmaputra confluence. Depart from Dibrugarh airport with memories of Arunachal\'s wildest adventure.',
        activities: ['Morning drive to Pasighat', 'Siang-Brahmaputra confluence viewpoint', 'Pasighat souvenir shopping', 'Afternoon flight from Dibrugarh'],
        meals: 'Breakfast at hotel, Lunch at Pasighat',
        accommodation: 'Departure',
      },
    ],
  },
  {
    id: 'grand-explorer',
    title: 'Grand Arunachal Explorer',
    subtitle: 'The Complete Circuit – East to West',
    duration: '10 Days / 9 Nights',
    durationDays: 10,
    difficulty: 'Moderate',
    highlights: ['Tawang Monastery', 'Ziro Valley', 'Namdapha', 'Pasighat', 'Sela Pass', 'Tribal homestays'],
    bestTime: 'October – March',
    coverImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop&auto=format&q=80',
    tags: ['Complete Circuit', 'Culture', 'Wildlife', 'Mountains'],
    summary: '10-day comprehensive circuit of Arunachal Pradesh\'s greatest hits. From the Buddhist monasteries of Tawang in the west to the wildlife forests of Namdapha in the east, with Ziro\'s tribal valleys in between.',
    days: [
      {
        day: 1,
        title: 'Arrival & Drive to Bhalukpong',
        location: 'Guwahati → Bhalukpong',
        description: 'Arrive at Guwahati and drive to Bhalukpong — the western entry point to Arunachal Pradesh. Collect your Inner Line Permit and settle in for the first night.',
        activities: ['Guwahati airport pickup', 'Inner Line Permit verification at Bhalukpong checkpoint', 'Kameng River evening walk', 'Welcome dinner'],
        meals: 'Dinner at riverside resort',
        accommodation: 'Riverside Resort, Bhalukpong',
      },
      {
        day: 2,
        title: 'Bomdila & Dirang',
        location: 'Bhalukpong → Bomdila → Dirang',
        description: 'Drive through forested hills to Bomdila monastery town, then continue to the lush Dirang Valley, stopping at scenic viewpoints along the way.',
        activities: ['Upper Bomdila Monastery', 'RR Hills viewpoint', 'Dirang Dzong ancient fortress', 'Dirang hot springs'],
        meals: 'Breakfast at resort, Lunch in Bomdila, Dinner in Dirang',
        accommodation: 'Hotel, Dirang',
      },
      {
        day: 3,
        title: 'Sela Pass & Tawang',
        location: 'Dirang → Sela Pass → Tawang',
        description: 'The highlight drive of the trip — cross the legendary Sela Pass (4170m) with its sacred lake and snow-capped panoramas, then descend into the Tawang valley.',
        activities: ['Sela Pass crossing & lake photography', 'Jaswant Garh war memorial', 'Nuranang Waterfall stop', 'Tawang town evening exploration'],
        meals: 'Packed breakfast, Hot tea at Sela Pass café, Dinner in Tawang',
        accommodation: 'Hotel, Tawang',
      },
      {
        day: 4,
        title: 'Tawang Monastery & Bumla Pass',
        location: 'Tawang',
        description: 'The most iconic day of the circuit. Visit the grand Tawang Monastery in the morning, then drive to Bumla Pass on the Chinese border and the sacred Sangestar Tso Lake.',
        activities: ['Tawang Monastery full tour', 'Tawang War Memorial', 'Bumla Pass (special permit)', 'Sangestar Tso Lake'],
        meals: 'Breakfast & dinner at hotel, Lunch at monastery',
        accommodation: 'Hotel, Tawang',
      },
      {
        day: 5,
        title: 'Return via Sela & Drive to Itanagar',
        location: 'Tawang → Itanagar',
        description: 'Begin the central part of the circuit, driving via Sela Pass back down to Itanagar — the state capital with its hilltop Ita Fort and Donyi-Polo culture.',
        activities: ['Early departure from Tawang', 'Ita Fort (mud brick fort ruins) Itanagar', 'Jawaharlal Nehru State Museum', 'Gandhi Market local food tour'],
        meals: 'Packed meals en route, Dinner in Itanagar',
        accommodation: 'Hotel, Itanagar',
      },
      {
        day: 6,
        title: 'Ziro Valley – Apatani Tribal Immersion',
        location: 'Itanagar → Ziro',
        description: 'Drive to the sublime Ziro Valley and check into an Apatani homestay. Spend the afternoon walking through bamboo villages and learning about the remarkable Apatani farming system.',
        activities: ['Drive to Ziro Valley', 'Apatani village walk', 'Paddy-cum-fish farm tour', 'Traditional weaving demonstration'],
        meals: 'Breakfast at hotel, Lunch en route, Dinner at Apatani homestay',
        accommodation: 'Apatani Homestay, Ziro',
      },
      {
        day: 7,
        title: 'Ziro to Along – Siang River',
        location: 'Ziro → Along',
        description: 'Drive south to the Adi tribe town of Along on the Siang River. The dramatic descent from the highlands to the Siang gorge is a highlight of the journey.',
        activities: ['Morning Ziro valley sunrise walk', 'Drive via Daporijo to Along', 'Siang riverbank evening walk', 'Adi cultural evening'],
        meals: 'Breakfast at homestay, Lunch en route, Dinner in Along',
        accommodation: 'Hotel, Along',
      },
      {
        day: 8,
        title: 'Siang Rafting & Pasighat',
        location: 'Along → Pasighat',
        description: 'Enjoy a thrilling white-water rafting session on the Siang River before driving to Pasighat, the oldest town in Arunachal on the banks of the Brahmaputra.',
        activities: ['Grade II-III Siang River rafting', 'Drive to Pasighat', 'Siang-Brahmaputra confluence viewpoint', 'Adi craft market in Pasighat'],
        meals: 'Breakfast at hotel, Riverside lunch, Dinner in Pasighat',
        accommodation: 'Hotel, Pasighat',
      },
      {
        day: 9,
        title: 'Namdapha Wildlife Sanctuary',
        location: 'Pasighat → Miao (Namdapha)',
        description: 'Drive east to Miao and spend the afternoon on a guided safari in the buffer zone of Namdapha National Park — home to 4 big cat species and 500+ bird species.',
        activities: ['Drive to Miao (Namdapha)', 'Afternoon jungle walk in Namdapha buffer zone', 'Birdwatching along Noa-Dehing River', 'Night wildlife spotting walk'],
        meals: 'Breakfast at hotel, Lunch en route, Dinner at forest guesthouse',
        accommodation: 'Forest Rest House, Miao',
      },
      {
        day: 10,
        title: 'Namdapha Morning Safari & Departure',
        location: 'Miao → Dibrugarh',
        description: 'Dawn jungle walk in Namdapha before driving to Dibrugarh for your return flight. The circuit is complete — from Himalayan passes to tropical rainforests in 10 remarkable days.',
        activities: ['6am dawn jungle safari', 'Namdapha Nature Centre visit', 'Drive to Dibrugarh', 'Afternoon departure'],
        meals: 'Breakfast at guesthouse, Lunch en route',
        accommodation: 'Departure',
      },
    ],
  },
];
